- name: nginx setup
  host: local
  connection: local
  become: yes

  tasks:
    - name: nginx installation
      ansible.builtin.package:
        name: nginx
        state: present #to install the app
    - name: starting nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enable: yes
  
