- name: variables in sequence
  hosts: local
  connection: local
  vars:
  test: play_Variables
  vars_prompt:
    - name: test
      prompt: what is your name
      private: false
  vars_files:
    - Variable.yaml
  tasks:
  - name: Testing variable sequence
    ansible.builtin.debug:
    
      mes: " {{emp_name }} {{ emp_prof }}"
