- name: pratice
  hosts: local
  connection: local
  vars:
  #1. string variables
    playbook_variables: hello i am from playbook
  tasks: 
  - name: calling playbook variables 
    debug:
      msg: " playbook_variables_are: {{ playbook_variables }} "