- name: functions
  hosts: local
  connection: local

  tasks:
  - name: read yaml and take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yaml into json 
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json  }}"

  - name: save json to file
    ansible.builtin.copy:
      dest: ./stundent-data.json
      content: "{{ student_yaml | to_nice_json  }}"
