- name: functions
  hosts: local
  connection: local

  vars:
    name: "Sivakumar reddy M"
    gmail: Info@GMAIL.COM
  tasks:
  - name: convert uppercase
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert lowercase
    ansible.builtin.debug:
      msg: "{{ gmail | lower }}"

