- name: functions
  hosts: local
  connection: local

  tasks:
  - name: grep for root
    ansible.builtin.shell: cat /etc/passwd | grep ec2-user
    register: command_output

  - name: print the command_output
    ansible.builtin.debug:
      msg: "{{ command_output }}"

  